### ISSUE TITLE
P3-Project Planning user stories

### ISSUE THREAD

**Issue by dcmorse** [saran0103/liftoff-assignments#4]
Aha! You've created a Trello board to track your progress on Liftoff course assignments!

You did a fine job of that, but unfortunately that's not what was asked for in the assignment. 

The idea is to create a project tracking board full of user stories for your capstone project. So like the sole entry `create website template` could be what we want, sort of, because it pertains to your project. 

But that's not the way user stories are phrased. They're phrased from a user's point of view, so maybe:

- When a user visits the site, all the pages are presented with a menubar and consistent color palette, so that the user understands when they are on the education site, and when they have left. 

Here are some more examples:

- A visitor can log in so the site can associate their content to their user.
- A user can upload a curriculum document
- A user can download another user's document (if they have permission)
- A user can not download another user's document (if they don't have permission), instead they're sent to the "buy curriculum" page for that document. 

etc.

To recieve full credit, please update your board with better user stories. If you're confused, we can go over it in class or at a study session.

**Comment by saran0103** [comment]
Hi Dave
I have updated my Trello with tasks as discussed.I have created wireframes using moqups.I have updated the read me file with the Project tracker and wireframes.Please share your insights regarding the same.

**Comment by dcmorse** [comment]
I'm going through mail and excuse me if I've already said this in another place. I think the stories are close - still not perfect. Ideally stories should be phrased like:
```
[user type] would like to [do thing] so that [overall goal is reached]
```
The wireframes are pretty - I like your templates, but they're still not showing the heart of your project, I don't think. The idea is to get assumptions about what the project workflows out of everyone's heads and onto paper. Maybe we can talk about this in person some time? (Maybe we already did and I'm forgetting it? There are a lot of projects, it's starting to be a blur - my apologies if so).

**Comment by dcmorse** [comment]
I'm closing this issue to reflect the good updates to your trello board since we last spoke.
